import Head from "next/head";
import { Banner } from "@/components/index";
import BannerImage from "../assets/images/banner-image.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>الصفحة الرئيسية </title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>
        <Banner
          title=" كل ماتحتاج معرفته عن المنطقة الصناعية بجمصة"
          desc="تاسس المنطقه الصناعيه بجمصه عام 1996 على مساحه 727 فدانا, ويبلغ اجمالىالمشروعات المقامه 463مصنعا , وتنتج اكثر من 166 منتجا الاستهلاك 
          المحلى والتصدير , ويصل عدد العاملين بهم الى نحو عشر الاف عامل."
          image={BannerImage}
          isButton={true}
      
        />
      </div>
    </>
  );
}
